spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/store}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: always
    include-binding-errors: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics