INSERT INTO customer (id, name) VALUES (1, 'Latoya Schmidt');
INSERT INTO customer (id, name) VALUES (2, 'Sylvester Larkin');
INSERT INTO customer (id, name) VALUES (3, 'Robert Runolfsson MD');
INSERT INTO customer (id, name) VALUES (4, 'Olga Wuckert');
INSERT INTO customer (id, name) VALUES (5, 'Wilfred Mosciski');
INSERT INTO customer (id, name) VALUES (6, 'Barbara Yundt');
INSERT INTO customer (id, name) VALUES (7, 'Camille Rogahn');
INSERT INTO customer (id, name) VALUES (8, 'Roderick Bins');
INSERT INTO customer (id, name) VALUES (9, 'Sara Sporer');
INSERT INTO customer (id, name) VALUES (10, 'Dexter Schiller');
INSERT INTO customer (id, name) VALUES (11, 'Amanda O''Reilly');
INSERT INTO customer (id, name) VALUES (12, 'Leo Hills');
INSERT INTO customer (id, name) VALUES (13, 'Raul Feil');
INSERT INTO customer (id, name) VALUES (14, 'Terrell Denesik');
INSERT INTO customer (id, name) VALUES (15, 'Carroll Hilpert');
INSERT INTO customer (id, name) VALUES (16, 'Malcolm Aufderhar');
INSERT INTO customer (id, name) VALUES (17, 'Erick Franecki');
INSERT INTO customer (id, name) VALUES (18, 'Gordon Torp');
INSERT INTO customer (id, name) VALUES (19, 'Jennifer Miller');
INSERT INTO customer (id, name) VALUES (20, 'Johanna Effertz');
INSERT INTO customer (id, name) VALUES (21, 'Jonathan Mertz');
INSERT INTO customer (id, name) VALUES (22, 'Dwight Larson');
INSERT INTO customer (id, name) VALUES (23, 'Lauren Stanton');
INSERT INTO customer (id, name) VALUES (24, 'Jeannette Kuphal');
INSERT INTO customer (id, name) VALUES (25, 'Howard Schuster');
INSERT INTO customer (id, name) VALUES (26, 'Jennifer Cummerata');
INSERT INTO customer (id, name) VALUES (27, 'Dana Corwin');
INSERT INTO customer (id, name) VALUES (28, 'Shawn Hansen');
INSERT INTO customer (id, name) VALUES (29, 'Nettie Wiza');
INSERT INTO customer (id, name) VALUES (30, 'Desiree Ryan');
INSERT INTO customer (id, name) VALUES (31, 'Jessie Collier');
INSERT INTO customer (id, name) VALUES (32, 'Emma Thiel Sr.');
INSERT INTO customer (id, name) VALUES (33, 'Daniel Heathcote');
INSERT INTO customer (id, name) VALUES (34, 'Deborah Bernier');
INSERT INTO customer (id, name) VALUES (35, 'Mrs. Dennis Gerlach Jr.');
INSERT INTO customer (id, name) VALUES (36, 'Zachary Russel');
INSERT INTO customer (id, name) VALUES (37, 'Leonard Kling');
INSERT INTO customer (id, name) VALUES (38, 'Gloria Weimann');
INSERT INTO customer (id, name) VALUES (39, 'Mr. Vicki Kemmer');
INSERT INTO customer (id, name) VALUES (40, 'Derek Goodwin');
INSERT INTO customer (id, name) VALUES (41, 'Alison Mayert DVM');
INSERT INTO customer (id, name) VALUES (42, 'Preston Breitenberg');
INSERT INTO customer (id, name) VALUES (43, 'Dr. Pablo Ernser III');
INSERT INTO customer (id, name) VALUES (44, 'Roland Beatty');
INSERT INTO customer (id, name) VALUES (45, 'Herbert Goldner');
INSERT INTO customer (id, name) VALUES (46, 'Nancy Sporer');
INSERT INTO customer (id, name) VALUES (47, 'Rogelio Durgan II');
INSERT INTO customer (id, name) VALUES (48, 'Estelle Wunsch');
INSERT INTO customer (id, name) VALUES (49, 'Julio Ledner');
INSERT INTO customer (id, name) VALUES (50, 'Ollie Schowalter');
INSERT INTO customer (id, name) VALUES (51, 'Gilbert Harvey');
INSERT INTO customer (id, name) VALUES (52, 'Ruby Willms');
INSERT INTO customer (id, name) VALUES (53, 'Della Gibson');
INSERT INTO customer (id, name) VALUES (54, 'Paul Howell');
INSERT INTO customer (id, name) VALUES (55, 'Marco Swift');
INSERT INTO customer (id, name) VALUES (56, 'Earl McGlynn');
INSERT INTO customer (id, name) VALUES (57, 'Alfred Huels');
INSERT INTO customer (id, name) VALUES (58, 'Ms. Lester Pollich');
INSERT INTO customer (id, name) VALUES (59, 'Amos Schulist');
INSERT INTO customer (id, name) VALUES (60, 'Ms. Darrel Hettinger');
INSERT INTO customer (id, name) VALUES (61, 'Omar Boyle');
INSERT INTO customer (id, name) VALUES (62, 'Sandra Beer');
INSERT INTO customer (id, name) VALUES (63, 'Fredrick Gutkowski');
INSERT INTO customer (id, name) VALUES (64, 'Rebecca Mills');
INSERT INTO customer (id, name) VALUES (65, 'Mrs. Ann Barton');
INSERT INTO customer (id, name) VALUES (66, 'Ruby Collier');
INSERT INTO customer (id, name) VALUES (67, 'Lindsey Cartwright');
INSERT INTO customer (id, name) VALUES (68, 'Brittany Crona I');
INSERT INTO customer (id, name) VALUES (69, 'Amber Thompson');
INSERT INTO customer (id, name) VALUES (70, 'Vicki Flatley');
INSERT INTO customer (id, name) VALUES (71, 'Lucille Jenkins');
INSERT INTO customer (id, name) VALUES (72, 'Miss Irma Schinner');
INSERT INTO customer (id, name) VALUES (73, 'Sheryl Cronin');
INSERT INTO customer (id, name) VALUES (74, 'Walter VonRueden');
INSERT INTO customer (id, name) VALUES (75, 'Jonathan Spinka DDS');
INSERT INTO customer (id, name) VALUES (76, 'Rolando Kub');
INSERT INTO customer (id, name) VALUES (77, 'Dr. Lloyd Hyatt');
INSERT INTO customer (id, name) VALUES (78, 'Randall Konopelski');
INSERT INTO customer (id, name) VALUES (79, 'Cary Hackett');
INSERT INTO customer (id, name) VALUES (80, 'Silvia Fay');
INSERT INTO customer (id, name) VALUES (81, 'Perry Bednar');
INSERT INTO customer (id, name) VALUES (82, 'Teresa Adams');
INSERT INTO customer (id, name) VALUES (83, 'Irving Lowe');
INSERT INTO customer (id, name) VALUES (84, 'Roman Prosacco');
INSERT INTO customer (id, name) VALUES (85, 'Kelvin Wolf');
INSERT INTO customer (id, name) VALUES (86, 'Dr. Cheryl Sawayn');
INSERT INTO customer (id, name) VALUES (87, 'Terrence Braun');
INSERT INTO customer (id, name) VALUES (88, 'Joshua Krajcik');
INSERT INTO customer (id, name) VALUES (89, 'Ryan Kemmer');
INSERT INTO customer (id, name) VALUES (90, 'Leon Purdy');
INSERT INTO customer (id, name) VALUES (91, 'Mrs. Jenny Murazik');
INSERT INTO customer (id, name) VALUES (92, 'Tonya Kovacek III');
INSERT INTO customer (id, name) VALUES (93, 'Bob Johnson');
INSERT INTO customer (id, name) VALUES (94, 'Margaret Feest');
INSERT INTO customer (id, name) VALUES (95, 'Edna Goldner');
INSERT INTO customer (id, name) VALUES (96, 'Roman Klein');
INSERT INTO customer (id, name) VALUES (97, 'Miss Maxine Williamson');
INSERT INTO customer (id, name) VALUES (98, 'Teri Roob');
INSERT INTO customer (id, name) VALUES (99, 'Lorraine Hermiston');
INSERT INTO customer (id, name) VALUES (100, 'Keith Franecki I');
