INSERT INTO customer (id, name) VALUES (1, 'Veronica Batz');
INSERT INTO customer (id, name) VALUES (2, 'Christy Treutel');
INSERT INTO customer (id, name) VALUES (3, 'Norman Reichel');
INSERT INTO customer (id, name) VALUES (4, 'Cindy Schumm');
INSERT INTO customer (id, name) VALUES (5, 'Russell Cassin');
INSERT INTO customer (id, name) VALUES (6, 'Maria Leffler IV');
INSERT INTO customer (id, name) VALUES (7, 'Jean Kris');
INSERT INTO customer (id, name) VALUES (8, 'Travis Walker');
INSERT INTO customer (id, name) VALUES (9, 'Bertha Shanahan');
INSERT INTO customer (id, name) VALUES (10, 'Sylvia Moen');
INSERT INTO customer (id, name) VALUES (11, 'Joseph Wuckert');
INSERT INTO customer (id, name) VALUES (12, 'Roberto Stanton');
INSERT INTO customer (id, name) VALUES (13, 'Juan Sipes');
INSERT INTO customer (id, name) VALUES (14, 'Mrs. Brian Keebler V');
INSERT INTO customer (id, name) VALUES (15, 'Mrs. Thelma Kutch');
INSERT INTO customer (id, name) VALUES (16, 'Raul Franey');
INSERT INTO customer (id, name) VALUES (17, 'Marsha Parker');
INSERT INTO customer (id, name) VALUES (18, 'Karl Heaney');
INSERT INTO customer (id, name) VALUES (19, 'Sally Quitzon');
INSERT INTO customer (id, name) VALUES (20, 'Forrest Kiehn');
INSERT INTO customer (id, name) VALUES (21, 'Alton Prosacco');
INSERT INTO customer (id, name) VALUES (22, 'Lance Yundt');
INSERT INTO customer (id, name) VALUES (23, 'Miriam Zieme');
INSERT INTO customer (id, name) VALUES (24, 'Mrs. Alexis McCullough');
INSERT INTO customer (id, name) VALUES (25, 'Marcia Spinka');
INSERT INTO customer (id, name) VALUES (26, 'Ms. Elijah Koepp');
INSERT INTO customer (id, name) VALUES (27, 'Leticia Price');
INSERT INTO customer (id, name) VALUES (28, 'Ernestine Jacobson');
INSERT INTO customer (id, name) VALUES (29, 'Margie Tremblay');
INSERT INTO customer (id, name) VALUES (30, 'Roy Quitzon');
INSERT INTO customer (id, name) VALUES (31, 'Ira Luettgen');
INSERT INTO customer (id, name) VALUES (32, 'Hector Kilback');
INSERT INTO customer (id, name) VALUES (33, 'Kelly Lueilwitz');
INSERT INTO customer (id, name) VALUES (34, 'Yolanda Osinski');
INSERT INTO customer (id, name) VALUES (35, 'Alexander Turcotte');
INSERT INTO customer (id, name) VALUES (36, 'Alfonso Tillman');
INSERT INTO customer (id, name) VALUES (37, 'Julie Cormier PhD');
INSERT INTO customer (id, name) VALUES (38, 'Emmett Witting Sr.');
INSERT INTO customer (id, name) VALUES (39, 'Virginia Dicki');
INSERT INTO customer (id, name) VALUES (40, 'Dennis Zieme');
INSERT INTO customer (id, name) VALUES (41, 'Kristie Aufderhar');
INSERT INTO customer (id, name) VALUES (42, 'Alberta Morar');
INSERT INTO customer (id, name) VALUES (43, 'Dr. Luz Green');
INSERT INTO customer (id, name) VALUES (44, 'Wade Paucek');
INSERT INTO customer (id, name) VALUES (45, 'Guadalupe Lemke');
INSERT INTO customer (id, name) VALUES (46, 'Olive Bosco');
INSERT INTO customer (id, name) VALUES (47, 'Flora Satterfield');
INSERT INTO customer (id, name) VALUES (48, 'Annette Cruickshank');
INSERT INTO customer (id, name) VALUES (49, 'Mrs. Alicia Kub');
INSERT INTO customer (id, name) VALUES (50, 'Bert Hettinger');
INSERT INTO customer (id, name) VALUES (51, 'Michelle Yost DDS');
INSERT INTO customer (id, name) VALUES (52, 'Arnold Rogahn');
INSERT INTO customer (id, name) VALUES (53, 'Janis Ondricka');
INSERT INTO customer (id, name) VALUES (54, 'Sammy Powlowski');
INSERT INTO customer (id, name) VALUES (55, 'Sadie Gerlach');
INSERT INTO customer (id, name) VALUES (56, 'Nina MacGyver');
INSERT INTO customer (id, name) VALUES (57, 'Kenneth Auer');
INSERT INTO customer (id, name) VALUES (58, 'Krystal Anderson');
INSERT INTO customer (id, name) VALUES (59, 'Martha Ferry');
INSERT INTO customer (id, name) VALUES (60, 'Casey Kunde');
INSERT INTO customer (id, name) VALUES (61, 'Marcia Mills');
INSERT INTO customer (id, name) VALUES (62, 'Richard Quigley');
INSERT INTO customer (id, name) VALUES (63, 'Claude Schimmel');
INSERT INTO customer (id, name) VALUES (64, 'Greg Harvey');
INSERT INTO customer (id, name) VALUES (65, 'Clay Cartwright');
INSERT INTO customer (id, name) VALUES (66, 'Andrew Murray');
INSERT INTO customer (id, name) VALUES (67, 'Mr. Carlos Schroeder');
INSERT INTO customer (id, name) VALUES (68, 'Lorene Zieme');
INSERT INTO customer (id, name) VALUES (69, 'Colin O''Hara');
INSERT INTO customer (id, name) VALUES (70, 'Nicole Baumbach');
INSERT INTO customer (id, name) VALUES (71, 'Delia Mante');
INSERT INTO customer (id, name) VALUES (72, 'Nick Sporer');
INSERT INTO customer (id, name) VALUES (73, 'Della Bauch');
INSERT INTO customer (id, name) VALUES (74, 'Dallas Champlin');
INSERT INTO customer (id, name) VALUES (75, 'Wade Ritchie');
INSERT INTO customer (id, name) VALUES (76, 'Sandy Murray');
INSERT INTO customer (id, name) VALUES (77, 'Viola Lindgren');
INSERT INTO customer (id, name) VALUES (78, 'Donald DuBuque II');
INSERT INTO customer (id, name) VALUES (79, 'Mr. Suzanne Dickens');
INSERT INTO customer (id, name) VALUES (80, 'Salvatore Hagenes');
INSERT INTO customer (id, name) VALUES (81, 'Eugene Wolff');
INSERT INTO customer (id, name) VALUES (82, 'Debra Ruecker');
INSERT INTO customer (id, name) VALUES (83, 'Abel Jacobson');
INSERT INTO customer (id, name) VALUES (84, 'Jaime Schuppe');
INSERT INTO customer (id, name) VALUES (85, 'Joshua Schaden');
INSERT INTO customer (id, name) VALUES (86, 'Miranda Hagenes');
INSERT INTO customer (id, name) VALUES (87, 'Karl Bruen');
INSERT INTO customer (id, name) VALUES (88, 'Karla Ortiz DVM');
INSERT INTO customer (id, name) VALUES (89, 'Jacob Lang');
INSERT INTO customer (id, name) VALUES (90, 'Ms. Marie Hettinger');
INSERT INTO customer (id, name) VALUES (91, 'Sean Mosciski');
INSERT INTO customer (id, name) VALUES (92, 'Georgia Koch');
INSERT INTO customer (id, name) VALUES (93, 'Mr. Alfred Stokes');
INSERT INTO customer (id, name) VALUES (94, 'Marc Morissette');
INSERT INTO customer (id, name) VALUES (95, 'Ms. Kellie Reynolds');
INSERT INTO customer (id, name) VALUES (96, 'Ms. Gabriel Turcotte');
INSERT INTO customer (id, name) VALUES (97, 'Miss Darla Cruickshank');
INSERT INTO customer (id, name) VALUES (98, 'Virginia Steuber');
INSERT INTO customer (id, name) VALUES (99, 'Jennifer Carroll');
INSERT INTO customer (id, name) VALUES (100, 'Nicholas Roob');

SELECT setval(pg_get_serial_sequence('customer', 'id'), COALESCE((SELECT MAX(id) FROM customer), 0) + 1, false);
SELECT setval('order_id_seq', 10000);

